pipeline {
    agent any

    enviroment {
        DEPLOY_PATH = "/root/docker"
        VPS_IP = "152.42.202.77"
    }
    stages {
        stage('Hello') {
            steps {
                withCredentials(
                    [
                    usernamePassword(credentialsId:'SSH_KEY',usernameVariable:'KEY', passwordVariable:'SSH_USER'),
                    string(credentialsId:'secret_id', variable:'VARS')
                    ]
                    ){
                        sh """
                            ssh -o StrictHostKeyChecking=no -i ${SSH_KEY} ${SSH_USER}@${VPS_IP}
                            '
                                cd  ${DEPLOY_PATH} && git pull
                                docker-compose down
                                docker-compose build
                                docker-compose up -d
                            '
                        """
                    }
            }
        }
        
    }
}